# Generated by Django 6.1 on 2026-09-03 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('estimated_minutes', models.PositiveIntegerField()),
                ('base_xp', models.PositiveIntegerField()),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChoreInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('xp_value', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Open', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_approve_at', models.DateTimeField(blank=True, null=True)),
                ('approved_via', models.CharField(blank=True, choices=[('peer', 'Peer'), ('auto', 'Auto')], default='', max_length=10)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_chores', to='homework_quest.profile')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chores', to='homework_quest.profile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='homework_quest.choretemplate')),
            ],
        ),
    ]
