# Generated by Django 6.1 on 2026-09-03 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_quest', '0002_choretemplate_choreinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('standings_json', models.JSONField(default=dict)),
                ('winner_ids', models.JSONField(default=list)),
                ('selected_perk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='homework_quest.perk')),
            ],
        ),
    ]
